name: Terraform CI Pipeline
run-name: Terraform CI Pipeline
on: [push]

jobs:
  terraform:
    name: Terraform CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.2.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact

      - name: Terraform Plan
        run: terraform plan -var="access_key=${{secrets.ACCESS_KEY}}" -var="secret_key=${{secrets.SECRET_KEY}}"

      - name: Terraform Apply
        run: terraform apply --auto-approve -var="access_key=${{secrets.ACCESS_KEY}}" -var="secret_key=${{secrets.SECRET_KEY}}"
